version: '3.7'

services:
  app:
    build:
      context: .
    port:
      - "8000:8000"
    volumes:
      - .ecomm2:/ecomm2
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1



